---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "my-subpath/"
    schedule:
      interval: "weekly"
    groups:
      spring-boot:
        patterns:
          - "spring-boot*"
          - "org.springframework.boot*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
